# Generated by Django 4.0 on 2021-12-27 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_reg', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('profile', models.ImageField(max_length=64, upload_to='student_profile')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.CharField(max_length=64)),
                ('national_id', models.CharField(max_length=64)),
                ('year_academic', models.CharField(max_length=64)),
                ('department', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Themarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=64)),
                ('academic_year', models.CharField(max_length=200)),
                ('module_name', models.CharField(max_length=200)),
                ('module_code', models.CharField(max_length=200)),
                ('module_credits', models.CharField(max_length=200)),
                ('module_marks', models.CharField(max_length=200)),
                ('module_semester', models.CharField(max_length=200)),
                ('module_grade', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('student_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.students')),
            ],
        ),
    ]
