# Generated by Django 4.0 on 2021-12-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0002_auto_20211221_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='module_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
